feikki_tupas:
    resource: "@FeikkiTupasBundle/Resources/config/routing.yml"
    prefix:   /

_feikki.base:
    prefix: /
    resource: "@FeikkiSiteBundle/Resources/config/routing.yml"

_whatsup.query:
    prefix:   /whatsup/
    resource: "@WhatsUpQueryBundle/Resources/config/routing.yml"