parameters:
#    feikki_tupas.example.class: Feikki\TupasBundle\Example

services:
#    feikki_tupas.example:
#        class: %feikki_tupas.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
