_whatsup.query.index:
    pattern:  /
    defaults:
      _controller: WhatsUpQueryBundle:Default:index

_whatsup.query.whois:
    pattern:  /whois/{domain}
    defaults:
      _controller: WhatsUpQueryBundle:Backend:checkDomain
      _format: json
    requirements:
      method: GET
      _format: json
      domain: "[a-z0-9]+.[a-z]{2,6}"

_whatsup.query.some:
    pattern:  /socialmedia/{media}/{name}
    defaults:
      _controller: WhatsUpQueryBundle:Backend:checkSocialMedia
      #_format: json
    requirements:
      method: GET
      #_format: json
      #name: "[a-z0-9]+"
