_WhatsUpQueryBundle.query.whois:
    pattern:  /
    defaults:
      _controller: WhatsUpQueryBundle:Default:index
_WhatsUpQueryBundle.query.whois:
    pattern:  /whois/{domain}
    defaults:
      _controller: WhatsUpQueryBundle:Backend:checkDomain
      _format: json
